openapi: 3.0.0
info:
  title: canalia
  version: 0.0.0
tags:
  - name: User
paths:
  /user:
    get:
      operationId: Routes_getUser
      summary: ユーザー情報を取得する
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      tags:
        - User
components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          description: ユーザー名
        email:
          type: string
          description: メールアドレス
servers:
  - url: https://localhost:8080
    description: Development server
    variables: {}
