# https://taskfile.dev

version: '3'

vars:
  REQUIRED_NODE_VERSION: '20'
  REQUIRED_PNPM_VERSION: '10'
  REQUIRED_GO_VERSION: '1.24'

tasks:
  # === Setup Tasks ===
  setup:
    desc: 'Complete project setup for new developers'
    cmds:
      - task: check-prerequisites
      - task: install-deps
      - task: generate-types
      - task: validate-setup

  check-prerequisites:
    desc: 'Check if all required tools are installed'
    cmds:
      - |
        echo "🔍 Checking prerequisites..."
        # Check Node.js
        if ! command -v node &> /dev/null; then
          echo "❌ Node.js is not installed. Please install Node.js {{.REQUIRED_NODE_VERSION}} LTS or later."
          exit 1
        fi
        NODE_VERSION=$(node -v | sed 's/v//')
        echo "✅ Node.js: $NODE_VERSION"

        # Check pnpm
        if ! command -v pnpm &> /dev/null; then
          echo "❌ pnpm is not installed. Please install pnpm {{.REQUIRED_PNPM_VERSION}} or later."
          echo "   Run: npm install -g pnpm"
          exit 1
        fi
        PNPM_VERSION=$(pnpm -v)
        echo "✅ pnpm: $PNPM_VERSION"

        # Check Go
        if ! command -v go &> /dev/null; then
          echo "❌ Go is not installed. Please install Go {{.REQUIRED_GO_VERSION}} or later."
          exit 1
        fi
        GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
        echo "✅ Go: $GO_VERSION"

        # Check Taskfile
        if ! command -v task &> /dev/null; then
          echo "❌ Taskfile is not installed. Please install from https://taskfile.dev/"
          exit 1
        fi
        echo "✅ Taskfile: $(task --version)"

        # Check Docker
        if ! command -v docker &> /dev/null; then
          echo "❌ Docker is not installed. Please install from https://docs.docker.com/get-docker/"
          exit 1
        fi
        DOCKER_VERSION=$(docker --version | awk '{print $3}' | sed 's/,//')
        echo "✅ Docker: $DOCKER_VERSION"

        echo "🎉 All prerequisites are satisfied!"

  install-deps:
    desc: 'Install all project dependencies'
    cmds:
      - echo "📦 Installing dependencies..."
      - task: pnpm-install
      - task: tidy
      - echo "✅ Dependencies installed successfully!"

  generate-types:
    desc: 'Generate TypeScript and Go types from OpenAPI schema'
    cmds:
      - echo "🔧 Generating types from OpenAPI schema..."
      - task: openapi-gen
      - echo "✅ Types generated successfully!"

  validate-setup:
    desc: 'Validate that the setup is working correctly'
    cmds:
      - echo "🧪 Validating setup..."
      - task: build
      - task: lint
      - echo "🎉 Setup validation completed successfully!"

  # === Development Tasks ===
  dev:
    desc: 'Run full development environment with Docker (with hot reload)'
    cmds:
      - task: docker:dev

  dev:client:
    desc: 'Run only the Next.js frontend'
    cmds:
      - echo "🚀 Starting frontend development server..."
      - pnpm run dev

  dev:server:
    desc: 'Run only the Go API server'
    dir: ./apps/go-api
    cmds:
      - echo "🚀 Starting Go API server..."
      - go run main.go

  # === Build Tasks ===
  build:
    desc: 'Build both frontend and backend'
    cmds:
      - task: build:client
      - task: build:server

  build:client:
    desc: 'Build the Next.js application'
    cmds:
      - echo "🏗️  Building frontend..."
      - pnpm -C apps/next-app build

  build:server:
    desc: 'Build the Go API server'
    dir: ./apps/go-api
    cmds:
      - echo "🏗️  Building Go API..."
      - go build -o canalia main.go

  # === Code Quality Tasks ===
  lint:
    desc: 'Run all linting and formatting checks'
    cmds:
      - echo "🔍 Running code quality checks..."
      - pnpm -C apps/next-app run check
      - pnpm -C apps/next-app run lint
      - echo "✅ All checks passed!"

  format:
    desc: 'Format all code'
    cmds:
      - echo "✨ Formatting code..."
      - pnpm -C apps/next-app run format

  # === Testing Tasks ===
  test:
    desc: 'Run all tests'
    cmds:
      - echo "🧪 Running tests..."
      - pnpm -C apps/next-app test

  storybook:
    desc: 'Start Storybook component development'
    cmds:
      - echo "📚 Starting Storybook..."
      - pnpm -C apps/next-app storybook

  # === Dependency Management ===
  pnpm-install:
    desc: 'Install Node.js dependencies'
    cmds:
      - pnpm i

  tidy:
    desc: 'Clean up Go dependencies'
    dir: ./apps/go-api
    cmds:
      - go mod tidy

  # === OpenAPI Code Generation ===
  openapi-gen:
    desc: 'Generate types from OpenAPI schema'
    cmds:
      - task: openapi-gen:client
      - task: openapi-gen:server

  openapi-gen:client:
    desc: 'Generate TypeScript types for frontend'
    cmds:
      - pnpm run openapi-gen

  openapi-gen:server:
    desc: 'Generate Go types for backend'
    dir: ./apps/go-api
    cmds:
      - go tool oapi-codegen -config oapi-config.yaml ../../schema/openapi.yaml

  # === Docker Tasks ===
  docker:up:
    desc: 'Start PostgreSQL for development'
    cmds:
      - echo "🐳 Starting development database..."
      - docker-compose -f docker-compose.dev.yml up -d postgres
      - echo "✅ Database is running at localhost:5432"

  docker:down:
    desc: 'Stop development database'
    cmds:
      - echo "🐳 Stopping development database..."
      - docker-compose -f docker-compose.dev.yml down

  docker:restart:
    desc: 'Restart development database'
    cmds:
      - task: docker:down
      - task: docker:up

  docker:logs:
    desc: 'Show database logs'
    cmds:
      - docker-compose -f docker-compose.dev.yml logs -f postgres

  docker:clean:
    desc: 'Stop and remove all development containers and volumes'
    cmds:
      - echo "🧹 Cleaning development environment..."
      - docker-compose -f docker-compose.dev.yml down -v --remove-orphans
      - echo "✅ Development environment cleaned!"

  docker:dev:
    desc: 'Start full development environment (PostgreSQL + Go API + Next.js)'
    cmds:
      - echo "🚀 Starting full development environment..."
      - docker-compose -f docker-compose.dev.yml up -d
      - echo "✅ Development environment is running:"
      - echo "   PostgreSQL at localhost:5432"
      - echo "   Go API at localhost:8080"
      - echo "   Next.js at localhost:3000"

  docker:dev:logs:
    desc: 'Show logs for all development services'
    cmds:
      - docker-compose -f docker-compose.dev.yml logs -f

  docker:dev:build:
    desc: 'Rebuild development containers'
    cmds:
      - echo "🔨 Rebuilding development containers..."
      - docker-compose -f docker-compose.dev.yml build --no-cache
      - echo "✅ Containers rebuilt!"

  # === Database Tasks ===
  db:dev:setup:
    desc: 'Setup development database (start Docker + run migrations)'
    cmds:
      - task: docker:up
      - task: db:dev:wait-ready
      - task: db:dev:migrate:up

  db:dev:wait-ready:
    desc: 'Wait for development database to be ready'
    cmds:
      - |
        echo "⏳ Waiting for database to be ready..."
        until docker exec canalia-postgres-dev pg_isready -U canalia_user -d canalia_db; do
          echo "  Database is not ready yet, waiting..."
          sleep 2
        done
        echo "✅ Database is ready!"

  db:dev:migrate:up:
    desc: 'Run database migrations (development)'
    dir: ./apps/go-api
    vars:
      DEV_DATABASE_URL: 'postgres://canalia_user:canalia_password@localhost:5432/canalia_db?sslmode=disable'
    cmds:
      - go run -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate -path internal/db/migrations -database "{{.DEV_DATABASE_URL}}" up

  db:dev:migrate:down:
    desc: 'Rollback database migrations (development)'
    dir: ./apps/go-api
    vars:
      DEV_DATABASE_URL: 'postgres://canalia_user:canalia_password@localhost:5432/canalia_db?sslmode=disable'
    cmds:
      - go run -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate -path internal/db/migrations -database "{{.DEV_DATABASE_URL}}" down

  db:migrate:create:
    desc: 'Create a new migration file'
    dir: ./apps/go-api
    cmds:
      - go tool migrate create -ext sql -dir internal/db/migrations -seq {{.CLI_ARGS}}

  db:dev:migrate:force:
    desc: 'Force database migration version (development)'
    dir: ./apps/go-api
    vars:
      DEV_DATABASE_URL: 'postgres://canalia_user:canalia_password@localhost:5432/canalia_db?sslmode=disable'
    cmds:
      - go run -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate -path internal/db/migrations -database "{{.DEV_DATABASE_URL}}" force {{.CLI_ARGS}}

  db:dev:migrate:version:
    desc: 'Show current migration version (development)'
    dir: ./apps/go-api
    vars:
      DEV_DATABASE_URL: 'postgres://canalia_user:canalia_password@localhost:5432/canalia_db?sslmode=disable'
    cmds:
      - go run -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate -path internal/db/migrations -database "{{.DEV_DATABASE_URL}}" version

  db:generate:
    desc: 'Generate Go code from SQL queries using sqlc'
    dir: ./apps/go-api
    cmds:
      - go tool sqlc generate

  db:dev:reset:
    desc: 'Reset development database (down all migrations, then up)'
    cmds:
      - task: db:dev:migrate:down
      - task: db:dev:migrate:up

  db:dev:clean:
    desc: 'Clean all data from development database tables'
    cmds:
      - |
        echo "🧹 Cleaning development database..."
        docker exec canalia-postgres-dev psql -U canalia_user -d canalia_db -c "
        DO \$\$
        DECLARE
          table_names TEXT;
        BEGIN
          SELECT string_agg(table_name, ', ')
          INTO table_names
          FROM information_schema.tables
          WHERE table_schema = 'public'
            AND table_type = 'BASE TABLE'
            AND table_name != 'schema_migrations';
          
          IF table_names IS NOT NULL THEN
            EXECUTE 'TRUNCATE TABLE ' || table_names || ' RESTART IDENTITY CASCADE';
            RAISE NOTICE 'Truncated tables: %', table_names;
          ELSE
            RAISE NOTICE 'No tables found to truncate';
          END IF;
        END;
        \$\$;
        "
        echo "✅ Database cleaned successfully!"

  # === Cleanup Tasks ===
  clean:
    desc: 'Clean all build artifacts and dependencies'
    cmds:
      - echo "🧹 Cleaning project..."
      - rm -rf node_modules apps/next-app/node_modules
      - rm -rf apps/next-app/.next apps/next-app/dist
      - rm -f apps/go-api/canalia
      - echo "✅ Project cleaned!"

  # === Help ===
  help:
    desc: 'Show available tasks'
    cmds:
      - task --list
