# https://taskfile.dev

version: '3'

tasks:
  dev:
    cmds:
      - task: dev:server
      - task: dev:client
  dev:client:
    cmds:
      - pnpm run dev
  dev:server:
    dir: ./apps/go-api
    cmds:
      - go run main.go

  pnpm-install:
    cmds:
      - pnpm i
  tidy:
    dir: ./apps/go-api
    cmds:
      - go mod tidy

  openapi-gen:
    cmds:
      - task: openapi-gen:client
      - task: openapi-gen:server
  openapi-gen:client:
    cmds:
      - pnpm run openapi-gen
  openapi-gen:server:
    dir: ./apps/go-api
    cmds:
      - go tool oapi-codegen -config oapi-config.yaml ../../schema/openapi.yaml
