# https://taskfile.dev

version: '3'

tasks:
  dev:
    deps:
      - dev:server
      - dev:client
  dev:client:
    cmds:
      - pnpm run dev
  dev:server:
    dir: ./go-api
    cmds:
      - go run main.go
  tidy:
    dir: ./go-api
    cmds:
      - go mod tidy
  openapi-gen:client:
    cmds:
      - pnpm run openapi-gen
  openapi-gen:server:
    dir: ./go-api
    cmds:
      - go tool oapi-codegen -package generated -generate types,server ../schema/openapi.yaml > generated/openapi.gen.go
