# https://taskfile.dev

version: '3'

tasks:
  dev:
    deps:
      - dev:server
      - dev:client
  dev:client:
    dir: ./js
    cmds:
      - pnpm run dev
  dev:server:
    dir: ./go
    cmds:
      - go run main.go
  tidy:
    dir: ./go
    cmds:
      - go mod tidy
  openapi-gen:client:
    dir: ./js
    cmds:
      - pnpm run openapi-gen
