# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: types
generate:
  models: true
  # Only generate types, not server handlers
output: internal/types/openapi.gen.go