// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

// User defines model for User.
type User struct {
	// Email メールアドレス
	Email string `json:"email"`

	// Name ユーザー名
	Name string `json:"name"`
}
