// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	RoleScopes = "Role.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// User defines model for User.
type User struct {
	// ContactEmail 連絡先メールアドレス
	ContactEmail *openapi_types.Email `json:"contactEmail"`

	// CreatedAt 作成日時
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Email Auth0から取得したメールアドレス
	Email *openapi_types.Email `json:"email,omitempty"`

	// FamilyName 姓
	FamilyName *string `json:"familyName,omitempty"`

	// GivenName 名
	GivenName *string `json:"givenName,omitempty"`

	// Id ユーザーID
	Id *int `json:"id,omitempty"`

	// IsActive ユーザーがアクティブかどうか
	IsActive *bool `json:"isActive,omitempty"`

	// IsVerified メールアドレスが認証済みかどうか
	IsVerified *bool `json:"isVerified,omitempty"`

	// PhoneNumber 電話番号
	PhoneNumber *string `json:"phoneNumber"`

	// UpdatedAt 更新日時
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// UserRegistrationInput defines model for UserRegistrationInput.
type UserRegistrationInput struct {
	ContactEmail *openapi_types.Email `json:"contactEmail,omitempty" validate:"omitempty,email"`
	FamilyName   string               `json:"familyName" validate:"required,min=1,max=100"`
	GivenName    string               `json:"givenName" validate:"required,min=1,max=100"`
	PhoneNumber  *string              `json:"phoneNumber,omitempty" validate:"omitempty,max=20"`
}

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody = UserRegistrationInput
